# Generated by Django 5.1.6 on 2025-12-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='Conversation',
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
