# Generated by Django 5.1.6 on 2025-12-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversation_table_alter_message_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='conversation',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
